export const PENDING='PENDING';
export const SUCCESS='SUCCESS';
export const FAILURE='FAILURE';


export const REGISTER_START='REGISTER_START';
export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const REGISTER_FAILURE='REGISTER_FAILURE';


export const LOGIN_START='LOGIN_START';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAILURE='LOGIN_FAILURE';

export const LOGOUT_START='LOGOUT_START';
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS';
export const LOGOUT_FAILURE='LOGOUT_FAILURE';

export const SET_USER="SET_USER";

export const GOOGLE_SIGNIN_START='GOOGLE_SIGNIN__START';
export const GOOGLE_SIGNIN_SUCCESS='GOOGLE_SIGNIN_SUCCESS';
export const GOOGLE_SIGNIN_FAILURE='GOOGLE_SIGNIN_FAILURE';



